stages:
  - build
  - deploy

.docker-login: &docker-login
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json

build:
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [ "/bin/sh", "-c" ]
  stage: build
  <<: *docker-login
  script:
    - sed -i "s|_TOKEN_|${SHARED_REGISTRY_TOKEN}|" ${CI_PROJECT_DIR}/Dockerfile
    - sed -i "s|_APP_RELEASE_TAG_|${CI_COMMIT_SHORT_SHA}|" ${CI_PROJECT_DIR}/Dockerfile
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --build-arg "SENTRY_ENVIRONMENT=dev"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}"
  tags:
    - sello-logistics-dev
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(dev|stage|test)$/

deploy:
  image:
    name: portainer/kubectl-shell:latest
    entrypoint: [ "/bin/sh", "-c" ]
  stage: deploy
  needs:
    - build
  script:
    - mv $ADMIN_CONF /home/shell/admin.conf && export KUBECONFIG=/home/shell/admin.conf
    - sed -i "s|latest|${CI_COMMIT_SHORT_SHA}|" deploy/k8s/$CI_COMMIT_BRANCH.yml
    - kubectl apply -f deploy/k8s/$CI_COMMIT_BRANCH.yml
  tags:
    - sello-logistics-dev
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(dev|stage|test)$/